const fs = require('fs');
const f = 'src/app/page.tsx';
const existing = fs.readFileSync(f, 'utf8');
const lines = [];
lines.push('');
lines.push('export default function Home() {');
lines.push('  const [lang, setLang] = useState("ja");');
lines.push('  const [email, setEmail] = useState("");');
lines.push('  const [submitted, setSubmitted] = useState(false);');
lines.push('  const t = i18n[lang];');
lines.push('  const handleWaitlist = (e: React.FormEvent) => { e.preventDefault(); if (email) setSubmitted(true); };');
lines.push('  const features = [{icon:"\ud83d\udcdd",t:t.f1t,d:t.f1d},{icon:"\ud83d\udcca",t:t.f2t,d:t.f2d},{icon:"\ud83c\udfa8",t:t.f3t,d:t.f3d},{icon:"\ud83c\udf10",t:t.f4t,d:t.f4d}];');
lines.push('  const steps = [{n:"1",t:t.s1t,d:t.s1d},{n:"2",t:t.s2t,d:t.s2d},{n:"3",t:t.s3t,d:t.s3d}];');
lines.push('  const plans = [');
lines.push('    {name:"Free",price:t.fp,per:t.per,items:[t.f1,t.f2,t.f3],btn:t.fb,featured:false},');
lines.push('    {name:"Pro",price:t.pp,per:t.per,items:[t.p1,t.p2,t.p3,t.p4],btn:t.pb,featured:true},');
lines.push('    {name:"Business",price:t.bp,per:t.per,items:[t.b1,t.b2,t.b3,t.b4],btn:t.bb,featured:false},');
lines.push('  ];');
lines.push('  return (');
lines.push('    <div style={{background:"#f8fafc",minHeight:"100vh"}}>');
lines.push('      <nav style={{background:"#fff",borderBottom:"1px solid #e2e8f0",padding:"0 24px",display:"flex",alignItems:"center",justifyContent:"space-between",height:60,position:"sticky",top:0,zIndex:100}}>');
lines.push('        <div style={{fontSize:22,fontWeight:800}}><span style={{color:"#2563eb"}}>Voice</span><span style={{color:"#1e293b"}}>Wall</span></div>');
lines.push('        <div style={{display:"flex",gap:8,alignItems:"center"}}>');
lines.push('          <a href="#features" style={{padding:"8px 16px",borderRadius:8,fontSize:14,textDecoration:"none",color:"#64748b",fontWeight:500}}>{lang==="ja"?"\u6a5f\u80fd":"Features"}</a>');
lines.push('          <a href="#pricing" style={{padding:"8px 16px",borderRadius:8,fontSize:14,textDecoration:"none",color:"#64748b",fontWeight:500}}>{lang==="ja"?"\u6599\u91d1":"Pricing"}</a>');
lines.push('          <a href="#waitlist" style={{padding:"8px 16px",borderRadius:8,fontSize:14,textDecoration:"none",color:"#64748b",fontWeight:500}}>{lang==="ja"?"\u4e8b\u524d\u767b\u9332":"Waitlist"}</a>');
lines.push('          <button onClick={()=>setLang(lang==="ja"?"en":"ja")} style={{padding:"6px 12px",borderRadius:6,border:"1px solid #e2e8f0",background:"#fff",cursor:"pointer",fontSize:13,fontWeight:600,color:"#64748b"}}>{lang==="ja"?"EN":"JP"}</button>');
lines.push('        </div>');
lines.push('      </nav>');
lines.push('      <section style={{textAlign:"center",padding:"80px 20px 60px",maxWidth:800,margin:"0 auto"}}>');
lines.push('        <h1 style={{fontSize:"clamp(32px,5vw,52px)",fontWeight:800,lineHeight:1.2,marginBottom:16,color:"#1e293b"}}>{t.heroTitle}<span style={{color:"#2563eb"}}>{t.a1}</span>{t.mid}<span style={{color:"#2563eb"}}>{t.a2}</span>{t.end}</h1>');
lines.push('        <p style={{fontSize:18,color:"#64748b",maxWidth:600,margin:"0 auto 32px"}}>{t.heroSub}</p>');
lines.push('        <a href="#waitlist" style={{display:"inline-block",padding:"14px 32px",borderRadius:8,background:"#2563eb",color:"#fff",fontSize:16,fontWeight:600,textDecoration:"none"}}>{t.cta}</a>');
lines.push('        <p style={{fontSize:13,color:"#94a3b8",marginTop:8}}>{t.ctaSub}</p>');
lines.push('      </section>');
lines.push('      <section id="features" style={{maxWidth:1100,margin:"0 auto",padding:"40px 20px 80px",display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:24}}>');
lines.push('        {features.map((f,i)=><div key={i} style={{background:"#fff",borderRadius:12,padding:32,border:"1px solid #e2e8f0"}}><div style={{width:48,height:48,borderRadius:12,background:"#dbeafe",display:"flex",alignItems:"center",justifyContent:"center",fontSize:24,marginBottom:16}}>{f.icon}</div><h3 style={{fontSize:18,marginBottom:8,color:"#1e293b"}}>{f.t}</h3><p style={{color:"#64748b",fontSize:14,lineHeight:1.6}}>{f.d}</p></div>)}');
lines.push('      </section>');
lines.push('      <section style={{background:"#fff",padding:"60px 20px",borderTop:"1px solid #e2e8f0",borderBottom:"1px solid #e2e8f0"}}>');
lines.push('        <div style={{maxWidth:900,margin:"0 auto",textAlign:"center"}}>');
lines.push('          <h2 style={{fontSize:32,fontWeight:800,marginBottom:48,color:"#1e293b"}}>{t.howT}</h2>');
lines.push('          <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:40}}>');
lines.push('            {steps.map((s,i)=><div key={i}><div style={{width:48,height:48,borderRadius:"50%",background:"#2563eb",color:"#fff",display:"flex",alignItems:"center",justifyContent:"center",fontSize:20,fontWeight:700,margin:"0 auto 16px"}}>{s.n}</div><h3 style={{fontSize:18,marginBottom:8,color:"#1e293b"}}>{s.t}</h3><p style={{color:"#64748b",fontSize:14}}>{s.d}</p></div>)}');
lines.push('          </div>');
lines.push('        </div>');
lines.push('      </section>');
lines.push('      <section style={{maxWidth:1100,margin:"0 auto",padding:"60px 20px"}}>');
lines.push('        <h2 style={{fontSize:32,fontWeight:800,textAlign:"center",marginBottom:40,color:"#1e293b"}}>{t.socialT}</h2>');
lines.push('        <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:20}}>');
lines.push('          {testimonials.map((r,i)=><div key={i} style={{background:"#fff",borderRadius:12,padding:24,border:"1px solid #e2e8f0"}}><div style={{color:"#f59e0b",letterSpacing:2,marginBottom:12,fontSize:16}}>{"\\u2605".repeat(r.stars)}{"\\u2606".repeat(5-r.stars)}</div><p style={{fontSize:14,color:"#1e293b",lineHeight:1.7,marginBottom:16,fontStyle:"italic"}}>&ldquo;{lang==="en"?r.textEn:r.text}&rdquo;</p><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:36,height:36,borderRadius:"50%",background:"#dbeafe",display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,fontWeight:700,color:"#2563eb"}}>{r.avatar}</div><div><div style={{fontSize:14,fontWeight:600,color:"#1e293b"}}>{lang==="en"?r.nameEn:r.name}</div><div style={{fontSize:12,color:"#94a3b8"}}>{lang==="en"?r.companyEn:r.company}</div></div></div></div>)}');
lines.push('        </div>');
lines.push('      </section>');
lines.push('      <section id="pricing" style={{background:"#fff",padding:"60px 20px",borderTop:"1px solid #e2e8f0"}}>');
lines.push('        <div style={{maxWidth:960,margin:"0 auto",textAlign:"center"}}>');
lines.push('          <h2 style={{fontSize:32,fontWeight:800,marginBottom:8,color:"#1e293b"}}>{t.priceT}</h2>');
lines.push('          <p style={{color:"#64748b",marginBottom:40}}>{t.priceS}</p>');
lines.push('          <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:24}}>');
lines.push('            {plans.map((p,i)=><div key={i} style={{background:"#fff",borderRadius:12,padding:32,border:p.featured?"2px solid #2563eb":"1px solid #e2e8f0",textAlign:"left"}}>{p.featured&&<span style={{display:"inline-block",background:"#2563eb",color:"#fff",fontSize:11,fontWeight:700,padding:"3px 10px",borderRadius:99,marginBottom:12}}>{t.pop}</span>}<h3 style={{fontSize:20,color:"#1e293b"}}>{p.name}</h3><div style={{fontSize:36,fontWeight:800,margin:"12px 0",color:"#1e293b"}}>{p.price}<span style={{fontSize:14,color:"#94a3b8",fontWeight:400}}> {p.per}</span></div><ul style={{listStyle:"none",padding:0,margin:"20px 0"}}>{p.items.map((item,j)=><li key={j} style={{padding:"6px 0",fontSize:14,color:"#64748b"}}>\u2713 {item}</li>)}</ul><a href="#waitlist" style={{display:"block",textAlign:"center",padding:"12px 24px",borderRadius:8,background:p.featured?"#2563eb":"#fff",color:p.featured?"#fff":"#1e293b",border:p.featured?"none":"1px solid #e2e8f0",fontWeight:600,fontSize:15,textDecoration:"none"}}>{p.btn}</a></div>)}');
lines.push('          </div>');
lines.push('        </div>');
lines.push('      </section>');
lines.push('      <section id="waitlist" style={{padding:"60px 20px",maxWidth:500,margin:"0 auto",textAlign:"center"}}>');
lines.push('        <h2 style={{fontSize:28,fontWeight:800,marginBottom:8,color:"#1e293b"}}>{t.wt}</h2>');
lines.push('        <p style={{color:"#64748b",marginBottom:24}}>{t.ws}</p>');
lines.push('        {!submitted?<form onSubmit={handleWaitlist} style={{display:"flex",gap:8}}><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder={t.eph} required style={{flex:1,padding:"12px 16px",borderRadius:8,border:"1px solid #e2e8f0",fontSize:15,outline:"none"}}/><button type="submit" style={{padding:"12px 24px",borderRadius:8,background:"#2563eb",color:"#fff",border:"none",fontSize:15,fontWeight:600,cursor:"pointer"}}>{t.wb}</button></form>:<div style={{background:"#d1fae5",color:"#065f46",padding:"16px 24px",borderRadius:8,fontWeight:500}}>{t.wth}</div>}');
lines.push('      </section>');
lines.push('      <section style={{background:"#1e293b",padding:"60px 20px",textAlign:"center"}}>');
lines.push('        <h2 style={{fontSize:28,fontWeight:800,color:"#fff",marginBottom:12}}>{t.ctaT}</h2>');
lines.push('        <p style={{color:"#94a3b8",marginBottom:24}}>{t.ctaS}</p>');
lines.push('        <a href="#waitlist" style={{display:"inline-block",padding:"14px 32px",borderRadius:8,background:"#2563eb",color:"#fff",fontSize:16,fontWeight:600,textDecoration:"none"}}>{t.ctaB}</a>');
lines.push('      </section>');
lines.push('      <footer style={{background:"#0f172a",padding:"40px 20px",color:"#94a3b8",fontSize:14}}>');
lines.push('        <div style={{maxWidth:1100,margin:"0 auto",display:"flex",justifyContent:"space-between",flexWrap:"wrap",gap:24}}>');
lines.push('          <div><div style={{fontSize:20,fontWeight:800,marginBottom:8}}><span style={{color:"#60a5fa"}}>Voice</span><span style={{color:"#fff"}}>Wall</span></div><p style={{maxWidth:300}}>{t.foot}</p></div>');
lines.push('          <p>\u00a9 2026 VoiceWall. All rights reserved.</p>');
lines.push('        </div>');
lines.push('      </footer>');
lines.push('    </div>');
lines.push('  );');
lines.push('}');
fs.writeFileSync(f, existing + lines.join('\n'));
console.log('Created: src/app/page.tsx (complete!)');
